name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 'current'

      - name: Build
        run: gradle --no-daemon build

      - uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/ShutUpAnnoyingMod-*.jar
